_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml

herb_guest_book:
    resource: "@HerbGuestBookBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /gbook

herb_frontend:
    resource: "@HerbFrontendBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /

herb_backend:
    resource: "@HerbBackendBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /aaddmmiinnppaaggee

herb_backend_indexpic:
    resource: "@HerbBackendBundle/Controller/IndexpicController.php"
    type: annotation


herb_backend_products:
    resource: "@HerbBackendBundle/Controller/ProductsController.php"
    type: annotation

herb_backend_guest_book:
    resource: "@HerbGuestBookBundle/Controller/AdminController.php"
    type: annotation
    