jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]

    providers:
        in_memory:
            memory:
                users:
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # login:
        #     pattern:  ^/demo/secured/login$
        #     security: false

        # secured_area:
        #     pattern:    ^/demo/secured/
        #     form_login:
        #         check_path: /demo/secured/login_check
        #         login_path: /demo/secured/login
        #     logout:
        #         path:   /demo/secured/logout
        #         target: /demo/
        login:
            pattern: ^/aaddmmiinnppaaggee/login$
            security: false
        secured_area:
            pattern: ^/aaddmmiinnppaaggee
            form_login:
                check_path: /aaddmmiinnppaaggee/login_check
                login_path: /aaddmmiinnppaaggee/login
            logout:
                path:   /aaddmmiinnppaaggee/logout
                target: /aaddmmiinnppaaggee/login
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
